language: php

services: mysql

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

branches:
  only:
    - master

sudo: false

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction
  - mysql -uroot < tests/fixtures.sql

script:
  - ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover; fi;'
