language: php

services: mysql

before_script:
  - composer self-update
  - composer install --dev --prefer-source
  - /etc/init.d/mysql start || 1
  - mysql -utravis -p'' < tests/fixtures.sql

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5

script:
  - phpunit -c tests/phpunit.xml --coverage-text
